# Generated by Django 5.0.3 on 2025-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')], default=1),
        ),
    ]
